// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Calibration status for compass.
enum CalibrationStatus: Int {
  /// Calibration is not needed.
  case notNeeded = 0
  /// Calibration is recommended.
  case recommended = 1
  /// Calibration is required for accurate readings.
  case required = 2
}

/// Data class representing sensor data from native platform.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SensorData {
  /// Device heading in degrees (0-360).
  var heading: Double
  /// Heading adjusted for camera mode.
  var headingForCameraMode: Double
  /// Accuracy of the heading in degrees.
  /// -1 indicates invalid/unavailable.
  var accuracy: Double
  /// Timestamp in milliseconds since epoch.
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SensorData? {
    let heading = pigeonVar_list[0] as! Double
    let headingForCameraMode = pigeonVar_list[1] as! Double
    let accuracy = pigeonVar_list[2] as! Double
    let timestamp: Int64? = nilOrValue(pigeonVar_list[3])

    return SensorData(
      heading: heading,
      headingForCameraMode: headingForCameraMode,
      accuracy: accuracy,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      heading,
      headingForCameraMode,
      accuracy,
      timestamp,
    ]
  }
}

/// Configuration for sensor updates.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SensorConfig {
  /// Update interval in milliseconds.
  var updateIntervalMs: Int64
  /// Whether to use true north (vs magnetic north).
  var useTrueNorth: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SensorConfig? {
    let updateIntervalMs = pigeonVar_list[0] as! Int64
    let useTrueNorth = pigeonVar_list[1] as! Bool

    return SensorConfig(
      updateIntervalMs: updateIntervalMs,
      useTrueNorth: useTrueNorth
    )
  }
  func toList() -> [Any?] {
    return [
      updateIntervalMs,
      useTrueNorth,
    ]
  }
}

/// Result of permission request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PermissionResult {
  /// Whether permission was granted.
  var granted: Bool
  /// Optional message about the result.
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionResult? {
    let granted = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])

    return PermissionResult(
      granted: granted,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      granted,
      message,
    ]
  }
}

private class ArSensorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CalibrationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SensorData.fromList(self.readValue() as! [Any?])
    case 131:
      return SensorConfig.fromList(self.readValue() as! [Any?])
    case 132:
      return PermissionResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ArSensorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CalibrationStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SensorData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? SensorConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PermissionResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ArSensorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ArSensorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ArSensorApiPigeonCodecWriter(data: data)
  }
}

class ArSensorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ArSensorApiPigeonCodec(readerWriter: ArSensorApiPigeonCodecReaderWriter())
}


/// Host API - methods called from Dart to native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArSensorHostApi {
  /// Starts sensor updates with the given configuration.
  func startSensorUpdates(config: SensorConfig) throws
  /// Stops sensor updates.
  func stopSensorUpdates() throws
  /// Checks if sensors are available on this device.
  func areSensorsAvailable() throws -> Bool
  /// Gets the current calibration status.
  func getCalibrationStatus() throws -> CalibrationStatus
  /// Requests location permission.
  func requestLocationPermission(completion: @escaping (Result<PermissionResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArSensorHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ArSensorApiPigeonCodec.shared }
  /// Sets up an instance of `ArSensorHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArSensorHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts sensor updates with the given configuration.
    let startSensorUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.startSensorUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSensorUpdatesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! SensorConfig
        do {
          try api.startSensorUpdates(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSensorUpdatesChannel.setMessageHandler(nil)
    }
    /// Stops sensor updates.
    let stopSensorUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.stopSensorUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopSensorUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.stopSensorUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopSensorUpdatesChannel.setMessageHandler(nil)
    }
    /// Checks if sensors are available on this device.
    let areSensorsAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.areSensorsAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      areSensorsAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.areSensorsAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      areSensorsAvailableChannel.setMessageHandler(nil)
    }
    /// Gets the current calibration status.
    let getCalibrationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.getCalibrationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCalibrationStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCalibrationStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCalibrationStatusChannel.setMessageHandler(nil)
    }
    /// Requests location permission.
    let requestLocationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.requestLocationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestLocationPermissionChannel.setMessageHandler { _, reply in
        api.requestLocationPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestLocationPermissionChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API - methods called from native to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ArSensorFlutterApiProtocol {
  /// Called when new sensor data is available.
  func onSensorUpdate(data dataArg: SensorData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when calibration is needed.
  func onCalibrationNeeded(status statusArg: CalibrationStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when an error occurs.
  func onError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ArSensorFlutterApi: ArSensorFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ArSensorApiPigeonCodec {
    return ArSensorApiPigeonCodec.shared
  }
  /// Called when new sensor data is available.
  func onSensorUpdate(data dataArg: SensorData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onSensorUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when calibration is needed.
  func onCalibrationNeeded(status statusArg: CalibrationStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onCalibrationNeeded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when an error occurs.
  func onError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
