// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.pie.technology.ar.location.view.ar_location_view

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Calibration status for compass. */
enum class CalibrationStatus(val raw: Int) {
  /** Calibration is not needed. */
  NOT_NEEDED(0),
  /** Calibration is recommended. */
  RECOMMENDED(1),
  /** Calibration is required for accurate readings. */
  REQUIRED(2);

  companion object {
    fun ofRaw(raw: Int): CalibrationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Data class representing sensor data from native platform.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SensorData (
  /** Device heading in degrees (0-360). */
  val heading: Double,
  /** Heading adjusted for camera mode. */
  val headingForCameraMode: Double,
  /**
   * Accuracy of the heading in degrees.
   * -1 indicates invalid/unavailable.
   */
  val accuracy: Double,
  /** Timestamp in milliseconds since epoch. */
  val timestamp: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SensorData {
      val heading = pigeonVar_list[0] as Double
      val headingForCameraMode = pigeonVar_list[1] as Double
      val accuracy = pigeonVar_list[2] as Double
      val timestamp = pigeonVar_list[3] as Long?
      return SensorData(heading, headingForCameraMode, accuracy, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      heading,
      headingForCameraMode,
      accuracy,
      timestamp,
    )
  }
}

/**
 * Configuration for sensor updates.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SensorConfig (
  /** Update interval in milliseconds. */
  val updateIntervalMs: Long,
  /** Whether to use true north (vs magnetic north). */
  val useTrueNorth: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SensorConfig {
      val updateIntervalMs = pigeonVar_list[0] as Long
      val useTrueNorth = pigeonVar_list[1] as Boolean
      return SensorConfig(updateIntervalMs, useTrueNorth)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      updateIntervalMs,
      useTrueNorth,
    )
  }
}

/**
 * Result of permission request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PermissionResult (
  /** Whether permission was granted. */
  val granted: Boolean,
  /** Optional message about the result. */
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionResult {
      val granted = pigeonVar_list[0] as Boolean
      val message = pigeonVar_list[1] as String?
      return PermissionResult(granted, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      granted,
      message,
    )
  }
}
private open class ArSensorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CalibrationStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SensorData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SensorConfig.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CalibrationStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is SensorData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is SensorConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PermissionResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API - methods called from Dart to native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ArSensorHostApi {
  /** Starts sensor updates with the given configuration. */
  fun startSensorUpdates(config: SensorConfig)
  /** Stops sensor updates. */
  fun stopSensorUpdates()
  /** Checks if sensors are available on this device. */
  fun areSensorsAvailable(): Boolean
  /** Gets the current calibration status. */
  fun getCalibrationStatus(): CalibrationStatus
  /** Requests location permission. */
  fun requestLocationPermission(callback: (Result<PermissionResult>) -> Unit)

  companion object {
    /** The codec used by ArSensorHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ArSensorApiPigeonCodec()
    }
    /** Sets up an instance of `ArSensorHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ArSensorHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.startSensorUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as SensorConfig
            val wrapped: List<Any?> = try {
              api.startSensorUpdates(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.stopSensorUpdates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopSensorUpdates()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.areSensorsAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.areSensorsAvailable())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.getCalibrationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCalibrationStatus())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ar_location_view.ArSensorHostApi.requestLocationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestLocationPermission{ result: Result<PermissionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API - methods called from native to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ArSensorFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ArSensorFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ArSensorApiPigeonCodec()
    }
  }
  /** Called when new sensor data is available. */
  fun onSensorUpdate(dataArg: SensorData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onSensorUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when calibration is needed. */
  fun onCalibrationNeeded(statusArg: CalibrationStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onCalibrationNeeded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when an error occurs. */
  fun onError(messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ar_location_view.ArSensorFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
